<?php

/**
 * @file
 * Contains ata.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function ata_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the ata module.
    case 'help.page.ata':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Modul ata menggunakan drupal console') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function ata_theme() {
  return [
    'ata' => [
      'render element' => 'children',
    ],
  ];
}
